# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAccount_Totals', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Account_Type', models.CharField(max_length=45)),
                ('Current_Or_Long_Term', models.CharField(max_length=45)),
                ('Account_Name', models.CharField(max_length=180)),
                ('Amount', models.FloatField()),
                ('Notes', models.CharField(max_length=300)),
                ('URL', models.CharField(max_length=300)),
            ],
        ),
    ]
